//------------------------------------------------------------------------------
//   This code was generated by a tool.
//
//   Changes to this file may cause incorrect behavior and will be lost if
//   the code is regenerated. Any updates should be done in
//   "templates/*.go.template" so they can be included in the generated
//   code.
//------------------------------------------------------------------------------

package streampeer

/*
#include <stdio.h>
#include <stdlib.h>
#include <gdnative/gdnative.h>
#include <nativescript/godot_nativescript.h>
*/
import "C"

import (
	"github.com/shadowapex/godot-go/godot/classes/class"
	"log"
	"reflect"

	"github.com/shadowapex/godot-go/godot/classes/reference"
)

/*
   StreamPeer is an abstraction and base class for stream-based protocols (such as TCP or Unix Sockets). It provides an API for sending and receiving data through streams as raw data or strings.
*/
type StreamPeer struct {
	reference.Reference
}

func (o *StreamPeer) baseClass() string {
	return "StreamPeer"
}

// SetOwner will internally set the Godot object inside the struct.
// This is used to call parent methods.
func (o *StreamPeer) setOwner(object *C.godot_object) {
	o.owner = object
}

func (o *StreamPeer) getOwner() *C.godot_object {
	return o.owner
}

/*
   Get a signed 16 bit value from the stream.
*/
func (o *StreamPeer) Get16() int64 {
	log.Println("Calling StreamPeer.Get16()")

	// Build out the method's arguments
	goArguments := make([]reflect.Value, 0, 0)

	// Call the parent method.

	goRet := class.CallParentMethod(o, o.baseClass(), "get_16", goArguments, "int64")

	returnValue := goRet.Interface().(int64)

	log.Println("  Got return value: ", returnValue)
	return returnValue

}

/*
   Get a signed 32 bit value from the stream.
*/
func (o *StreamPeer) Get32() int64 {
	log.Println("Calling StreamPeer.Get32()")

	// Build out the method's arguments
	goArguments := make([]reflect.Value, 0, 0)

	// Call the parent method.

	goRet := class.CallParentMethod(o, o.baseClass(), "get_32", goArguments, "int64")

	returnValue := goRet.Interface().(int64)

	log.Println("  Got return value: ", returnValue)
	return returnValue

}

/*
   Get a signed 64 bit value from the stream.
*/
func (o *StreamPeer) Get64() int64 {
	log.Println("Calling StreamPeer.Get64()")

	// Build out the method's arguments
	goArguments := make([]reflect.Value, 0, 0)

	// Call the parent method.

	goRet := class.CallParentMethod(o, o.baseClass(), "get_64", goArguments, "int64")

	returnValue := goRet.Interface().(int64)

	log.Println("  Got return value: ", returnValue)
	return returnValue

}

/*
   Get a signed byte from the stream.
*/
func (o *StreamPeer) Get8() int64 {
	log.Println("Calling StreamPeer.Get8()")

	// Build out the method's arguments
	goArguments := make([]reflect.Value, 0, 0)

	// Call the parent method.

	goRet := class.CallParentMethod(o, o.baseClass(), "get_8", goArguments, "int64")

	returnValue := goRet.Interface().(int64)

	log.Println("  Got return value: ", returnValue)
	return returnValue

}

/*
   Return the amount of bytes this [StreamPeer] has available.
*/
func (o *StreamPeer) GetAvailableBytes() int64 {
	log.Println("Calling StreamPeer.GetAvailableBytes()")

	// Build out the method's arguments
	goArguments := make([]reflect.Value, 0, 0)

	// Call the parent method.

	goRet := class.CallParentMethod(o, o.baseClass(), "get_available_bytes", goArguments, "int64")

	returnValue := goRet.Interface().(int64)

	log.Println("  Got return value: ", returnValue)
	return returnValue

}

/*
   Return a chunk data with the received bytes. The amount of bytes to be received can be requested in the "bytes" argument. If not enough bytes are available, the function will block until the desired amount is received. This function returns two values, an Error code and a data array.
*/
func (o *StreamPeer) GetData(bytes int64) *Array {
	log.Println("Calling StreamPeer.GetData()")

	// Build out the method's arguments
	goArguments := make([]reflect.Value, 1, 1)
	goArguments[0] = reflect.ValueOf(bytes)

	// Call the parent method.

	goRet := class.CallParentMethod(o, o.baseClass(), "get_data", goArguments, "*Array")

	returnValue := goRet.Interface().(*Array)

	log.Println("  Got return value: ", returnValue)
	return returnValue

}

/*
   Get a double-precision float from the stream.
*/
func (o *StreamPeer) GetDouble() float64 {
	log.Println("Calling StreamPeer.GetDouble()")

	// Build out the method's arguments
	goArguments := make([]reflect.Value, 0, 0)

	// Call the parent method.

	goRet := class.CallParentMethod(o, o.baseClass(), "get_double", goArguments, "float64")

	returnValue := goRet.Interface().(float64)

	log.Println("  Got return value: ", returnValue)
	return returnValue

}

/*
   Get a single-precision float from the stream.
*/
func (o *StreamPeer) GetFloat() float64 {
	log.Println("Calling StreamPeer.GetFloat()")

	// Build out the method's arguments
	goArguments := make([]reflect.Value, 0, 0)

	// Call the parent method.

	goRet := class.CallParentMethod(o, o.baseClass(), "get_float", goArguments, "float64")

	returnValue := goRet.Interface().(float64)

	log.Println("  Got return value: ", returnValue)
	return returnValue

}

/*
   Return a chunk data with the received bytes. The amount of bytes to be received can be requested in the "bytes" argument. If not enough bytes are available, the function will return how many were actually received. This function returns two values, an Error code, and a data array.
*/
func (o *StreamPeer) GetPartialData(bytes int64) *Array {
	log.Println("Calling StreamPeer.GetPartialData()")

	// Build out the method's arguments
	goArguments := make([]reflect.Value, 1, 1)
	goArguments[0] = reflect.ValueOf(bytes)

	// Call the parent method.

	goRet := class.CallParentMethod(o, o.baseClass(), "get_partial_data", goArguments, "*Array")

	returnValue := goRet.Interface().(*Array)

	log.Println("  Got return value: ", returnValue)
	return returnValue

}

/*
   Get a string with byte-length "bytes" from the stream.
*/
func (o *StreamPeer) GetString(bytes int64) string {
	log.Println("Calling StreamPeer.GetString()")

	// Build out the method's arguments
	goArguments := make([]reflect.Value, 1, 1)
	goArguments[0] = reflect.ValueOf(bytes)

	// Call the parent method.

	goRet := class.CallParentMethod(o, o.baseClass(), "get_string", goArguments, "string")

	returnValue := goRet.Interface().(string)

	log.Println("  Got return value: ", returnValue)
	return returnValue

}

/*
   Get an unsigned 16 bit value from the stream.
*/
func (o *StreamPeer) GetU16() int64 {
	log.Println("Calling StreamPeer.GetU16()")

	// Build out the method's arguments
	goArguments := make([]reflect.Value, 0, 0)

	// Call the parent method.

	goRet := class.CallParentMethod(o, o.baseClass(), "get_u16", goArguments, "int64")

	returnValue := goRet.Interface().(int64)

	log.Println("  Got return value: ", returnValue)
	return returnValue

}

/*
   Get an unsigned 32 bit value from the stream.
*/
func (o *StreamPeer) GetU32() int64 {
	log.Println("Calling StreamPeer.GetU32()")

	// Build out the method's arguments
	goArguments := make([]reflect.Value, 0, 0)

	// Call the parent method.

	goRet := class.CallParentMethod(o, o.baseClass(), "get_u32", goArguments, "int64")

	returnValue := goRet.Interface().(int64)

	log.Println("  Got return value: ", returnValue)
	return returnValue

}

/*
   Get an unsigned 16 bit value from the stream.
*/
func (o *StreamPeer) GetU64() int64 {
	log.Println("Calling StreamPeer.GetU64()")

	// Build out the method's arguments
	goArguments := make([]reflect.Value, 0, 0)

	// Call the parent method.

	goRet := class.CallParentMethod(o, o.baseClass(), "get_u64", goArguments, "int64")

	returnValue := goRet.Interface().(int64)

	log.Println("  Got return value: ", returnValue)
	return returnValue

}

/*
   Get an unsigned byte from the stream.
*/
func (o *StreamPeer) GetU8() int64 {
	log.Println("Calling StreamPeer.GetU8()")

	// Build out the method's arguments
	goArguments := make([]reflect.Value, 0, 0)

	// Call the parent method.

	goRet := class.CallParentMethod(o, o.baseClass(), "get_u8", goArguments, "int64")

	returnValue := goRet.Interface().(int64)

	log.Println("  Got return value: ", returnValue)
	return returnValue

}

/*
   Get a utf8 string with byte-length "bytes" from the stream (this decodes the string sent as utf8).
*/
func (o *StreamPeer) GetUtf8String(bytes int64) string {
	log.Println("Calling StreamPeer.GetUtf8String()")

	// Build out the method's arguments
	goArguments := make([]reflect.Value, 1, 1)
	goArguments[0] = reflect.ValueOf(bytes)

	// Call the parent method.

	goRet := class.CallParentMethod(o, o.baseClass(), "get_utf8_string", goArguments, "string")

	returnValue := goRet.Interface().(string)

	log.Println("  Got return value: ", returnValue)
	return returnValue

}

/*
   Get a Variant from the stream.
*/
func (o *StreamPeer) GetVar() *Variant {
	log.Println("Calling StreamPeer.GetVar()")

	// Build out the method's arguments
	goArguments := make([]reflect.Value, 0, 0)

	// Call the parent method.

	goRet := class.CallParentMethod(o, o.baseClass(), "get_var", goArguments, "*Variant")

	returnValue := goRet.Interface().(*Variant)

	log.Println("  Got return value: ", returnValue)
	return returnValue

}

/*
   Return whether this [StreamPeer] is using big-endian format.
*/
func (o *StreamPeer) IsBigEndianEnabled() bool {
	log.Println("Calling StreamPeer.IsBigEndianEnabled()")

	// Build out the method's arguments
	goArguments := make([]reflect.Value, 0, 0)

	// Call the parent method.

	goRet := class.CallParentMethod(o, o.baseClass(), "is_big_endian_enabled", goArguments, "bool")

	returnValue := goRet.Interface().(bool)

	log.Println("  Got return value: ", returnValue)
	return returnValue

}

/*
   Put a signed 16 bit value into the stream.
*/
func (o *StreamPeer) Put16(val int64) {
	log.Println("Calling StreamPeer.Put16()")

	// Build out the method's arguments
	goArguments := make([]reflect.Value, 1, 1)
	goArguments[0] = reflect.ValueOf(val)

	// Call the parent method.

	o.callParentMethod(o.baseClass(), "put_16", goArguments, "")

	log.Println("  Function successfully completed.")

}

/*
   Put a signed 32 bit value into the stream.
*/
func (o *StreamPeer) Put32(val int64) {
	log.Println("Calling StreamPeer.Put32()")

	// Build out the method's arguments
	goArguments := make([]reflect.Value, 1, 1)
	goArguments[0] = reflect.ValueOf(val)

	// Call the parent method.

	o.callParentMethod(o.baseClass(), "put_32", goArguments, "")

	log.Println("  Function successfully completed.")

}

/*
   Put a signed 64 bit value into the stream.
*/
func (o *StreamPeer) Put64(val int64) {
	log.Println("Calling StreamPeer.Put64()")

	// Build out the method's arguments
	goArguments := make([]reflect.Value, 1, 1)
	goArguments[0] = reflect.ValueOf(val)

	// Call the parent method.

	o.callParentMethod(o.baseClass(), "put_64", goArguments, "")

	log.Println("  Function successfully completed.")

}

/*
   Put a signed byte into the stream.
*/
func (o *StreamPeer) Put8(val int64) {
	log.Println("Calling StreamPeer.Put8()")

	// Build out the method's arguments
	goArguments := make([]reflect.Value, 1, 1)
	goArguments[0] = reflect.ValueOf(val)

	// Call the parent method.

	o.callParentMethod(o.baseClass(), "put_8", goArguments, "")

	log.Println("  Function successfully completed.")

}

/*
   Send a chunk of data through the connection, blocking if necessary until the data is done sending. This function returns an Error code.
*/
func (o *StreamPeer) PutData(data *PoolByteArray) int64 {
	log.Println("Calling StreamPeer.PutData()")

	// Build out the method's arguments
	goArguments := make([]reflect.Value, 1, 1)
	goArguments[0] = reflect.ValueOf(data)

	// Call the parent method.

	goRet := class.CallParentMethod(o, o.baseClass(), "put_data", goArguments, "int64")

	returnValue := goRet.Interface().(int64)

	log.Println("  Got return value: ", returnValue)
	return returnValue

}

/*
   Put a double-precision float into the stream.
*/
func (o *StreamPeer) PutDouble(val float64) {
	log.Println("Calling StreamPeer.PutDouble()")

	// Build out the method's arguments
	goArguments := make([]reflect.Value, 1, 1)
	goArguments[0] = reflect.ValueOf(val)

	// Call the parent method.

	o.callParentMethod(o.baseClass(), "put_double", goArguments, "")

	log.Println("  Function successfully completed.")

}

/*
   Put a single-precision float into the stream.
*/
func (o *StreamPeer) PutFloat(val float64) {
	log.Println("Calling StreamPeer.PutFloat()")

	// Build out the method's arguments
	goArguments := make([]reflect.Value, 1, 1)
	goArguments[0] = reflect.ValueOf(val)

	// Call the parent method.

	o.callParentMethod(o.baseClass(), "put_float", goArguments, "")

	log.Println("  Function successfully completed.")

}

/*
   Send a chunk of data through the connection, if all the data could not be sent at once, only part of it will. This function returns two values, an Error code and an integer, describing how much data was actually sent.
*/
func (o *StreamPeer) PutPartialData(data *PoolByteArray) *Array {
	log.Println("Calling StreamPeer.PutPartialData()")

	// Build out the method's arguments
	goArguments := make([]reflect.Value, 1, 1)
	goArguments[0] = reflect.ValueOf(data)

	// Call the parent method.

	goRet := class.CallParentMethod(o, o.baseClass(), "put_partial_data", goArguments, "*Array")

	returnValue := goRet.Interface().(*Array)

	log.Println("  Got return value: ", returnValue)
	return returnValue

}

/*
   Put an unsigned 16 bit value into the stream.
*/
func (o *StreamPeer) PutU16(val int64) {
	log.Println("Calling StreamPeer.PutU16()")

	// Build out the method's arguments
	goArguments := make([]reflect.Value, 1, 1)
	goArguments[0] = reflect.ValueOf(val)

	// Call the parent method.

	o.callParentMethod(o.baseClass(), "put_u16", goArguments, "")

	log.Println("  Function successfully completed.")

}

/*
   Put an unsigned 32 bit value into the stream.
*/
func (o *StreamPeer) PutU32(val int64) {
	log.Println("Calling StreamPeer.PutU32()")

	// Build out the method's arguments
	goArguments := make([]reflect.Value, 1, 1)
	goArguments[0] = reflect.ValueOf(val)

	// Call the parent method.

	o.callParentMethod(o.baseClass(), "put_u32", goArguments, "")

	log.Println("  Function successfully completed.")

}

/*
   Put an unsigned 64 bit value into the stream.
*/
func (o *StreamPeer) PutU64(val int64) {
	log.Println("Calling StreamPeer.PutU64()")

	// Build out the method's arguments
	goArguments := make([]reflect.Value, 1, 1)
	goArguments[0] = reflect.ValueOf(val)

	// Call the parent method.

	o.callParentMethod(o.baseClass(), "put_u64", goArguments, "")

	log.Println("  Function successfully completed.")

}

/*
   Put an unsigned byte into the stream.
*/
func (o *StreamPeer) PutU8(val int64) {
	log.Println("Calling StreamPeer.PutU8()")

	// Build out the method's arguments
	goArguments := make([]reflect.Value, 1, 1)
	goArguments[0] = reflect.ValueOf(val)

	// Call the parent method.

	o.callParentMethod(o.baseClass(), "put_u8", goArguments, "")

	log.Println("  Function successfully completed.")

}

/*
   Put a zero-terminated utf8 string into the stream.
*/
func (o *StreamPeer) PutUtf8String(val string) {
	log.Println("Calling StreamPeer.PutUtf8String()")

	// Build out the method's arguments
	goArguments := make([]reflect.Value, 1, 1)
	goArguments[0] = reflect.ValueOf(val)

	// Call the parent method.

	o.callParentMethod(o.baseClass(), "put_utf8_string", goArguments, "")

	log.Println("  Function successfully completed.")

}

/*
   Put a Variant into the stream.
*/
func (o *StreamPeer) PutVar(val *Variant) {
	log.Println("Calling StreamPeer.PutVar()")

	// Build out the method's arguments
	goArguments := make([]reflect.Value, 1, 1)
	goArguments[0] = reflect.ValueOf(val)

	// Call the parent method.

	o.callParentMethod(o.baseClass(), "put_var", goArguments, "")

	log.Println("  Function successfully completed.")

}

/*
   Set this [StreamPeer] to use big-endian format. Default is false.
*/
func (o *StreamPeer) SetBigEndian(enable bool) {
	log.Println("Calling StreamPeer.SetBigEndian()")

	// Build out the method's arguments
	goArguments := make([]reflect.Value, 1, 1)
	goArguments[0] = reflect.ValueOf(enable)

	// Call the parent method.

	o.callParentMethod(o.baseClass(), "set_big_endian", goArguments, "")

	log.Println("  Function successfully completed.")

}

/*
   StreamPeerImplementer is an interface for StreamPeer objects.
*/
type StreamPeerImplementer interface {
	class.Class
}
