//------------------------------------------------------------------------------
//   This code was generated by a tool.
//
//   Changes to this file may cause incorrect behavior and will be lost if
//   the code is regenerated. Any updates should be done in
//   "templates/*.go.template" so they can be included in the generated
//   code.
//------------------------------------------------------------------------------

package convexpolygonshape

/*
#include <stdio.h>
#include <stdlib.h>
#include <gdnative/gdnative.h>
#include <nativescript/godot_nativescript.h>
*/
import "C"

import (
	"github.com/shadowapex/godot-go/godot/classes/class"
	"log"
	"reflect"

	"github.com/shadowapex/godot-go/godot/classes/shape"
)

/*
   Convex polygon shape resource, which can be added to a [PhysicsBody] or area.
*/
type ConvexPolygonShape struct {
	shape.Shape
}

func (o *ConvexPolygonShape) baseClass() string {
	return "ConvexPolygonShape"
}

// SetOwner will internally set the Godot object inside the struct.
// This is used to call parent methods.
func (o *ConvexPolygonShape) setOwner(object *C.godot_object) {
	o.owner = object
}

func (o *ConvexPolygonShape) getOwner() *C.godot_object {
	return o.owner
}

/*

 */
func (o *ConvexPolygonShape) GetPoints() *PoolVector3Array {
	log.Println("Calling ConvexPolygonShape.GetPoints()")

	// Build out the method's arguments
	goArguments := make([]reflect.Value, 0, 0)

	// Call the parent method.

	goRet := class.CallParentMethod(o, o.baseClass(), "get_points", goArguments, "*PoolVector3Array")

	returnValue := goRet.Interface().(*PoolVector3Array)

	log.Println("  Got return value: ", returnValue)
	return returnValue

}

/*

 */
func (o *ConvexPolygonShape) SetPoints(points *PoolVector3Array) {
	log.Println("Calling ConvexPolygonShape.SetPoints()")

	// Build out the method's arguments
	goArguments := make([]reflect.Value, 1, 1)
	goArguments[0] = reflect.ValueOf(points)

	// Call the parent method.

	o.callParentMethod(o.baseClass(), "set_points", goArguments, "")

	log.Println("  Function successfully completed.")

}

/*
   ConvexPolygonShapeImplementer is an interface for ConvexPolygonShape objects.
*/
type ConvexPolygonShapeImplementer interface {
	class.Class
}
