//------------------------------------------------------------------------------
//   This code was generated by a tool.
//
//   Changes to this file may cause incorrect behavior and will be lost if
//   the code is regenerated. Any updates should be done in
//   "templates/*.go.template" so they can be included in the generated
//   code.
//------------------------------------------------------------------------------

package physicsdirectbodystatesw

/*
#include <stdio.h>
#include <stdlib.h>
#include <gdnative/gdnative.h>
#include <nativescript/godot_nativescript.h>
*/
import "C"

import (
	"github.com/shadowapex/godot-go/godot/classes/class"
	"log"
	"reflect"

	"github.com/shadowapex/godot-go/godot/classes/physicsdirectbodystate"
)

/*

 */
type PhysicsDirectBodyStateSW struct {
	physicsdirectbodystate.PhysicsDirectBodyState
}

func (o *PhysicsDirectBodyStateSW) baseClass() string {
	return "PhysicsDirectBodyStateSW"
}

// SetOwner will internally set the Godot object inside the struct.
// This is used to call parent methods.
func (o *PhysicsDirectBodyStateSW) setOwner(object *C.godot_object) {
	o.owner = object
}

func (o *PhysicsDirectBodyStateSW) getOwner() *C.godot_object {
	return o.owner
}

/*
   PhysicsDirectBodyStateSWImplementer is an interface for PhysicsDirectBodyStateSW objects.
*/
type PhysicsDirectBodyStateSWImplementer interface {
	class.Class
}
