//------------------------------------------------------------------------------
//   This code was generated by a tool.
//
//   Changes to this file may cause incorrect behavior and will be lost if
//   the code is regenerated. Any updates should be done in
//   "templates/*.go.template" so they can be included in the generated
//   code.
//------------------------------------------------------------------------------

package treeitem

/*
#include <stdio.h>
#include <stdlib.h>
#include <gdnative/gdnative.h>
#include <nativescript/godot_nativescript.h>
*/
import "C"

import (
	"github.com/shadowapex/godot-go/godot/classes/class"
	"log"
	"reflect"

	"github.com/shadowapex/godot-go/godot/classes/object"
)

/*
   Control for a single item inside a [Tree]. May have child [TreeItem]\ s and be styled as well as contain buttons.
*/
type TreeItem struct {
	object.Object
}

func (o *TreeItem) baseClass() string {
	return "TreeItem"
}

// SetOwner will internally set the Godot object inside the struct.
// This is used to call parent methods.
func (o *TreeItem) setOwner(object *C.godot_object) {
	o.owner = object
}

func (o *TreeItem) getOwner() *C.godot_object {
	return o.owner
}

/*
   Adds a button with [Texture] [code]button[/code] at column [code]column[/code]. The [code]button_idx[/code] index is used to identify the button when calling other methods. If not specified, the next available index is used, which may be retrieved by calling [code]get_buton_count()[/code] immediately after this method. Optionally, the button can be [code]disabled[/code] and have a [code]tooltip[/code].
*/
func (o *TreeItem) AddButton(column int64, button *Texture, buttonIdx int64, disabled bool, tooltip string) {
	log.Println("Calling TreeItem.AddButton()")

	// Build out the method's arguments
	goArguments := make([]reflect.Value, 5, 5)
	goArguments[0] = reflect.ValueOf(column)
	goArguments[1] = reflect.ValueOf(button)
	goArguments[2] = reflect.ValueOf(buttonIdx)
	goArguments[3] = reflect.ValueOf(disabled)
	goArguments[4] = reflect.ValueOf(tooltip)

	// Call the parent method.

	o.callParentMethod(o.baseClass(), "add_button", goArguments, "")

	log.Println("  Function successfully completed.")

}

/*
   Resets the background color for the given column to default.
*/
func (o *TreeItem) ClearCustomBgColor(column int64) {
	log.Println("Calling TreeItem.ClearCustomBgColor()")

	// Build out the method's arguments
	goArguments := make([]reflect.Value, 1, 1)
	goArguments[0] = reflect.ValueOf(column)

	// Call the parent method.

	o.callParentMethod(o.baseClass(), "clear_custom_bg_color", goArguments, "")

	log.Println("  Function successfully completed.")

}

/*
   Resets the color for the given column to default.
*/
func (o *TreeItem) ClearCustomColor(column int64) {
	log.Println("Calling TreeItem.ClearCustomColor()")

	// Build out the method's arguments
	goArguments := make([]reflect.Value, 1, 1)
	goArguments[0] = reflect.ValueOf(column)

	// Call the parent method.

	o.callParentMethod(o.baseClass(), "clear_custom_color", goArguments, "")

	log.Println("  Function successfully completed.")

}

/*
   Deselects the given column.
*/
func (o *TreeItem) Deselect(column int64) {
	log.Println("Calling TreeItem.Deselect()")

	// Build out the method's arguments
	goArguments := make([]reflect.Value, 1, 1)
	goArguments[0] = reflect.ValueOf(column)

	// Call the parent method.

	o.callParentMethod(o.baseClass(), "deselect", goArguments, "")

	log.Println("  Function successfully completed.")

}

/*
   Removes the button at index [code]button_idx[/code] in column [code]column[/code].
*/
func (o *TreeItem) EraseButton(column int64, buttonIdx int64) {
	log.Println("Calling TreeItem.EraseButton()")

	// Build out the method's arguments
	goArguments := make([]reflect.Value, 2, 2)
	goArguments[0] = reflect.ValueOf(column)
	goArguments[1] = reflect.ValueOf(buttonIdx)

	// Call the parent method.

	o.callParentMethod(o.baseClass(), "erase_button", goArguments, "")

	log.Println("  Function successfully completed.")

}

/*
   Returns the [Texture] of the button at index [code]button_idx[/code] in column [code]column[/code].
*/
func (o *TreeItem) GetButton(column int64, buttonIdx int64) *Texture {
	log.Println("Calling TreeItem.GetButton()")

	// Build out the method's arguments
	goArguments := make([]reflect.Value, 2, 2)
	goArguments[0] = reflect.ValueOf(column)
	goArguments[1] = reflect.ValueOf(buttonIdx)

	// Call the parent method.

	goRet := class.CallParentMethod(o, o.baseClass(), "get_button", goArguments, "*Texture")

	returnValue := goRet.Interface().(*Texture)

	log.Println("  Got return value: ", returnValue)
	return returnValue

}

/*
   Returns the number of buttons in column [code]column[/code]. May be used to get the most recently added button's index, if no index was specified.
*/
func (o *TreeItem) GetButtonCount(column int64) int64 {
	log.Println("Calling TreeItem.GetButtonCount()")

	// Build out the method's arguments
	goArguments := make([]reflect.Value, 1, 1)
	goArguments[0] = reflect.ValueOf(column)

	// Call the parent method.

	goRet := class.CallParentMethod(o, o.baseClass(), "get_button_count", goArguments, "int64")

	returnValue := goRet.Interface().(int64)

	log.Println("  Got return value: ", returnValue)
	return returnValue

}

/*
   Returns the column's cell mode. See [code]CELL_MODE_*[/code] constants.
*/
func (o *TreeItem) GetCellMode(column int64) int64 {
	log.Println("Calling TreeItem.GetCellMode()")

	// Build out the method's arguments
	goArguments := make([]reflect.Value, 1, 1)
	goArguments[0] = reflect.ValueOf(column)

	// Call the parent method.

	goRet := class.CallParentMethod(o, o.baseClass(), "get_cell_mode", goArguments, "int64")

	returnValue := goRet.Interface().(int64)

	log.Println("  Got return value: ", returnValue)
	return returnValue

}

/*
   Returns the TreeItem's child items.
*/
func (o *TreeItem) GetChildren() *TreeItem {
	log.Println("Calling TreeItem.GetChildren()")

	// Build out the method's arguments
	goArguments := make([]reflect.Value, 0, 0)

	// Call the parent method.

	goRet := class.CallParentMethod(o, o.baseClass(), "get_children", goArguments, "*TreeItem")

	returnValue := goRet.Interface().(*TreeItem)

	log.Println("  Got return value: ", returnValue)
	return returnValue

}

/*
   Returns the custom background color of column [code]column[/code].
*/
func (o *TreeItem) GetCustomBgColor(column int64) *Color {
	log.Println("Calling TreeItem.GetCustomBgColor()")

	// Build out the method's arguments
	goArguments := make([]reflect.Value, 1, 1)
	goArguments[0] = reflect.ValueOf(column)

	// Call the parent method.

	goRet := class.CallParentMethod(o, o.baseClass(), "get_custom_bg_color", goArguments, "*Color")

	returnValue := goRet.Interface().(*Color)

	log.Println("  Got return value: ", returnValue)
	return returnValue

}

/*
   Returns the custom minimum height.
*/
func (o *TreeItem) GetCustomMinimumHeight() int64 {
	log.Println("Calling TreeItem.GetCustomMinimumHeight()")

	// Build out the method's arguments
	goArguments := make([]reflect.Value, 0, 0)

	// Call the parent method.

	goRet := class.CallParentMethod(o, o.baseClass(), "get_custom_minimum_height", goArguments, "int64")

	returnValue := goRet.Interface().(int64)

	log.Println("  Got return value: ", returnValue)
	return returnValue

}

/*
   Returns [code]true[/code] if [code]expand_right[/code] is set.
*/
func (o *TreeItem) GetExpandRight(column int64) bool {
	log.Println("Calling TreeItem.GetExpandRight()")

	// Build out the method's arguments
	goArguments := make([]reflect.Value, 1, 1)
	goArguments[0] = reflect.ValueOf(column)

	// Call the parent method.

	goRet := class.CallParentMethod(o, o.baseClass(), "get_expand_right", goArguments, "bool")

	returnValue := goRet.Interface().(bool)

	log.Println("  Got return value: ", returnValue)
	return returnValue

}

/*
   Returns the given column's icon [Texture]. Error if no icon is set.
*/
func (o *TreeItem) GetIcon(column int64) *Texture {
	log.Println("Calling TreeItem.GetIcon()")

	// Build out the method's arguments
	goArguments := make([]reflect.Value, 1, 1)
	goArguments[0] = reflect.ValueOf(column)

	// Call the parent method.

	goRet := class.CallParentMethod(o, o.baseClass(), "get_icon", goArguments, "*Texture")

	returnValue := goRet.Interface().(*Texture)

	log.Println("  Got return value: ", returnValue)
	return returnValue

}

/*
   Returns the column's icon's maximum width.
*/
func (o *TreeItem) GetIconMaxWidth(column int64) int64 {
	log.Println("Calling TreeItem.GetIconMaxWidth()")

	// Build out the method's arguments
	goArguments := make([]reflect.Value, 1, 1)
	goArguments[0] = reflect.ValueOf(column)

	// Call the parent method.

	goRet := class.CallParentMethod(o, o.baseClass(), "get_icon_max_width", goArguments, "int64")

	returnValue := goRet.Interface().(int64)

	log.Println("  Got return value: ", returnValue)
	return returnValue

}

/*
   Returns the icon [Texture] region as [Rect2].
*/
func (o *TreeItem) GetIconRegion(column int64) *Rect2 {
	log.Println("Calling TreeItem.GetIconRegion()")

	// Build out the method's arguments
	goArguments := make([]reflect.Value, 1, 1)
	goArguments[0] = reflect.ValueOf(column)

	// Call the parent method.

	goRet := class.CallParentMethod(o, o.baseClass(), "get_icon_region", goArguments, "*Rect2")

	returnValue := goRet.Interface().(*Rect2)

	log.Println("  Got return value: ", returnValue)
	return returnValue

}

/*

 */
func (o *TreeItem) GetMetadata(column int64) *Variant {
	log.Println("Calling TreeItem.GetMetadata()")

	// Build out the method's arguments
	goArguments := make([]reflect.Value, 1, 1)
	goArguments[0] = reflect.ValueOf(column)

	// Call the parent method.

	goRet := class.CallParentMethod(o, o.baseClass(), "get_metadata", goArguments, "*Variant")

	returnValue := goRet.Interface().(*Variant)

	log.Println("  Got return value: ", returnValue)
	return returnValue

}

/*
   Returns the next TreeItem in the tree.
*/
func (o *TreeItem) GetNext() *TreeItem {
	log.Println("Calling TreeItem.GetNext()")

	// Build out the method's arguments
	goArguments := make([]reflect.Value, 0, 0)

	// Call the parent method.

	goRet := class.CallParentMethod(o, o.baseClass(), "get_next", goArguments, "*TreeItem")

	returnValue := goRet.Interface().(*TreeItem)

	log.Println("  Got return value: ", returnValue)
	return returnValue

}

/*
   Returns the next visible TreeItem in the tree.
*/
func (o *TreeItem) GetNextVisible() *TreeItem {
	log.Println("Calling TreeItem.GetNextVisible()")

	// Build out the method's arguments
	goArguments := make([]reflect.Value, 0, 0)

	// Call the parent method.

	goRet := class.CallParentMethod(o, o.baseClass(), "get_next_visible", goArguments, "*TreeItem")

	returnValue := goRet.Interface().(*TreeItem)

	log.Println("  Got return value: ", returnValue)
	return returnValue

}

/*
   Returns the parent TreeItem.
*/
func (o *TreeItem) GetParent() *TreeItem {
	log.Println("Calling TreeItem.GetParent()")

	// Build out the method's arguments
	goArguments := make([]reflect.Value, 0, 0)

	// Call the parent method.

	goRet := class.CallParentMethod(o, o.baseClass(), "get_parent", goArguments, "*TreeItem")

	returnValue := goRet.Interface().(*TreeItem)

	log.Println("  Got return value: ", returnValue)
	return returnValue

}

/*
   Returns the previous TreeItem in the tree.
*/
func (o *TreeItem) GetPrev() *TreeItem {
	log.Println("Calling TreeItem.GetPrev()")

	// Build out the method's arguments
	goArguments := make([]reflect.Value, 0, 0)

	// Call the parent method.

	goRet := class.CallParentMethod(o, o.baseClass(), "get_prev", goArguments, "*TreeItem")

	returnValue := goRet.Interface().(*TreeItem)

	log.Println("  Got return value: ", returnValue)
	return returnValue

}

/*
   Returns the previous visible TreeItem in the tree.
*/
func (o *TreeItem) GetPrevVisible() *TreeItem {
	log.Println("Calling TreeItem.GetPrevVisible()")

	// Build out the method's arguments
	goArguments := make([]reflect.Value, 0, 0)

	// Call the parent method.

	goRet := class.CallParentMethod(o, o.baseClass(), "get_prev_visible", goArguments, "*TreeItem")

	returnValue := goRet.Interface().(*TreeItem)

	log.Println("  Got return value: ", returnValue)
	return returnValue

}

/*

 */
func (o *TreeItem) GetRange(column int64) float64 {
	log.Println("Calling TreeItem.GetRange()")

	// Build out the method's arguments
	goArguments := make([]reflect.Value, 1, 1)
	goArguments[0] = reflect.ValueOf(column)

	// Call the parent method.

	goRet := class.CallParentMethod(o, o.baseClass(), "get_range", goArguments, "float64")

	returnValue := goRet.Interface().(float64)

	log.Println("  Got return value: ", returnValue)
	return returnValue

}

/*

 */
func (o *TreeItem) GetRangeConfig(column int64) *Dictionary {
	log.Println("Calling TreeItem.GetRangeConfig()")

	// Build out the method's arguments
	goArguments := make([]reflect.Value, 1, 1)
	goArguments[0] = reflect.ValueOf(column)

	// Call the parent method.

	goRet := class.CallParentMethod(o, o.baseClass(), "get_range_config", goArguments, "*Dictionary")

	returnValue := goRet.Interface().(*Dictionary)

	log.Println("  Got return value: ", returnValue)
	return returnValue

}

/*
   Returns the given column's text.
*/
func (o *TreeItem) GetText(column int64) string {
	log.Println("Calling TreeItem.GetText()")

	// Build out the method's arguments
	goArguments := make([]reflect.Value, 1, 1)
	goArguments[0] = reflect.ValueOf(column)

	// Call the parent method.

	goRet := class.CallParentMethod(o, o.baseClass(), "get_text", goArguments, "string")

	returnValue := goRet.Interface().(string)

	log.Println("  Got return value: ", returnValue)
	return returnValue

}

/*
   Returns the given column's text alignment.
*/
func (o *TreeItem) GetTextAlign(column int64) int64 {
	log.Println("Calling TreeItem.GetTextAlign()")

	// Build out the method's arguments
	goArguments := make([]reflect.Value, 1, 1)
	goArguments[0] = reflect.ValueOf(column)

	// Call the parent method.

	goRet := class.CallParentMethod(o, o.baseClass(), "get_text_align", goArguments, "int64")

	returnValue := goRet.Interface().(int64)

	log.Println("  Got return value: ", returnValue)
	return returnValue

}

/*
   Returns the given column's tooltip.
*/
func (o *TreeItem) GetTooltip(column int64) string {
	log.Println("Calling TreeItem.GetTooltip()")

	// Build out the method's arguments
	goArguments := make([]reflect.Value, 1, 1)
	goArguments[0] = reflect.ValueOf(column)

	// Call the parent method.

	goRet := class.CallParentMethod(o, o.baseClass(), "get_tooltip", goArguments, "string")

	returnValue := goRet.Interface().(string)

	log.Println("  Got return value: ", returnValue)
	return returnValue

}

/*
   Returns [code]true[/code] if the button at index [code]button_idx[/code] for the given column is disabled.
*/
func (o *TreeItem) IsButtonDisabled(column int64, buttonIdx int64) bool {
	log.Println("Calling TreeItem.IsButtonDisabled()")

	// Build out the method's arguments
	goArguments := make([]reflect.Value, 2, 2)
	goArguments[0] = reflect.ValueOf(column)
	goArguments[1] = reflect.ValueOf(buttonIdx)

	// Call the parent method.

	goRet := class.CallParentMethod(o, o.baseClass(), "is_button_disabled", goArguments, "bool")

	returnValue := goRet.Interface().(bool)

	log.Println("  Got return value: ", returnValue)
	return returnValue

}

/*
   Returns [code]true[/code] if the given column is checked.
*/
func (o *TreeItem) IsChecked(column int64) bool {
	log.Println("Calling TreeItem.IsChecked()")

	// Build out the method's arguments
	goArguments := make([]reflect.Value, 1, 1)
	goArguments[0] = reflect.ValueOf(column)

	// Call the parent method.

	goRet := class.CallParentMethod(o, o.baseClass(), "is_checked", goArguments, "bool")

	returnValue := goRet.Interface().(bool)

	log.Println("  Got return value: ", returnValue)
	return returnValue

}

/*
   Returns [code]true[/code] if this TreeItem is collapsed.
*/
func (o *TreeItem) IsCollapsed() bool {
	log.Println("Calling TreeItem.IsCollapsed()")

	// Build out the method's arguments
	goArguments := make([]reflect.Value, 0, 0)

	// Call the parent method.

	goRet := class.CallParentMethod(o, o.baseClass(), "is_collapsed", goArguments, "bool")

	returnValue := goRet.Interface().(bool)

	log.Println("  Got return value: ", returnValue)
	return returnValue

}

/*

 */
func (o *TreeItem) IsCustomSetAsButton(column int64) bool {
	log.Println("Calling TreeItem.IsCustomSetAsButton()")

	// Build out the method's arguments
	goArguments := make([]reflect.Value, 1, 1)
	goArguments[0] = reflect.ValueOf(column)

	// Call the parent method.

	goRet := class.CallParentMethod(o, o.baseClass(), "is_custom_set_as_button", goArguments, "bool")

	returnValue := goRet.Interface().(bool)

	log.Println("  Got return value: ", returnValue)
	return returnValue

}

/*
   Returns [code]true[/code] if column [code]column[/code] is editable.
*/
func (o *TreeItem) IsEditable(column int64) bool {
	log.Println("Calling TreeItem.IsEditable()")

	// Build out the method's arguments
	goArguments := make([]reflect.Value, 1, 1)
	goArguments[0] = reflect.ValueOf(column)

	// Call the parent method.

	goRet := class.CallParentMethod(o, o.baseClass(), "is_editable", goArguments, "bool")

	returnValue := goRet.Interface().(bool)

	log.Println("  Got return value: ", returnValue)
	return returnValue

}

/*
   Returns [code]true[/code] if folding is disabled for this TreeItem.
*/
func (o *TreeItem) IsFoldingDisabled() bool {
	log.Println("Calling TreeItem.IsFoldingDisabled()")

	// Build out the method's arguments
	goArguments := make([]reflect.Value, 0, 0)

	// Call the parent method.

	goRet := class.CallParentMethod(o, o.baseClass(), "is_folding_disabled", goArguments, "bool")

	returnValue := goRet.Interface().(bool)

	log.Println("  Got return value: ", returnValue)
	return returnValue

}

/*
   Returns [code]true[/code] if column [code]column[/code] is selectable.
*/
func (o *TreeItem) IsSelectable(column int64) bool {
	log.Println("Calling TreeItem.IsSelectable()")

	// Build out the method's arguments
	goArguments := make([]reflect.Value, 1, 1)
	goArguments[0] = reflect.ValueOf(column)

	// Call the parent method.

	goRet := class.CallParentMethod(o, o.baseClass(), "is_selectable", goArguments, "bool")

	returnValue := goRet.Interface().(bool)

	log.Println("  Got return value: ", returnValue)
	return returnValue

}

/*
   Returns [code]true[/code] if column [code]column[/code] is selected.
*/
func (o *TreeItem) IsSelected(column int64) bool {
	log.Println("Calling TreeItem.IsSelected()")

	// Build out the method's arguments
	goArguments := make([]reflect.Value, 1, 1)
	goArguments[0] = reflect.ValueOf(column)

	// Call the parent method.

	goRet := class.CallParentMethod(o, o.baseClass(), "is_selected", goArguments, "bool")

	returnValue := goRet.Interface().(bool)

	log.Println("  Got return value: ", returnValue)
	return returnValue

}

/*
   Moves this TreeItem to the bottom in the [Tree] hierarchy.
*/
func (o *TreeItem) MoveToBottom() {
	log.Println("Calling TreeItem.MoveToBottom()")

	// Build out the method's arguments
	goArguments := make([]reflect.Value, 0, 0)

	// Call the parent method.

	o.callParentMethod(o.baseClass(), "move_to_bottom", goArguments, "")

	log.Println("  Function successfully completed.")

}

/*
   Moves this TreeItem to the top in the [Tree] hierarchy.
*/
func (o *TreeItem) MoveToTop() {
	log.Println("Calling TreeItem.MoveToTop()")

	// Build out the method's arguments
	goArguments := make([]reflect.Value, 0, 0)

	// Call the parent method.

	o.callParentMethod(o.baseClass(), "move_to_top", goArguments, "")

	log.Println("  Function successfully completed.")

}

/*
   Removes the child TreeItem at index [code]index[/code].
*/
func (o *TreeItem) RemoveChild(child *Object) {
	log.Println("Calling TreeItem.RemoveChild()")

	// Build out the method's arguments
	goArguments := make([]reflect.Value, 1, 1)
	goArguments[0] = reflect.ValueOf(child)

	// Call the parent method.

	o.callParentMethod(o.baseClass(), "remove_child", goArguments, "")

	log.Println("  Function successfully completed.")

}

/*
   Selects the column [code]column[/code].
*/
func (o *TreeItem) Select(column int64) {
	log.Println("Calling TreeItem.Select()")

	// Build out the method's arguments
	goArguments := make([]reflect.Value, 1, 1)
	goArguments[0] = reflect.ValueOf(column)

	// Call the parent method.

	o.callParentMethod(o.baseClass(), "select", goArguments, "")

	log.Println("  Function successfully completed.")

}

/*
   Sets the given column's button [Texture] at index [code]button_idx[/code] to [code]button[/code].
*/
func (o *TreeItem) SetButton(column int64, buttonIdx int64, button *Texture) {
	log.Println("Calling TreeItem.SetButton()")

	// Build out the method's arguments
	goArguments := make([]reflect.Value, 3, 3)
	goArguments[0] = reflect.ValueOf(column)
	goArguments[1] = reflect.ValueOf(buttonIdx)
	goArguments[2] = reflect.ValueOf(button)

	// Call the parent method.

	o.callParentMethod(o.baseClass(), "set_button", goArguments, "")

	log.Println("  Function successfully completed.")

}

/*
   Sets the given column's cell mode to [code]mode[/code]. See [code]CELL_MODE_*[/code] constants.
*/
func (o *TreeItem) SetCellMode(column int64, mode int64) {
	log.Println("Calling TreeItem.SetCellMode()")

	// Build out the method's arguments
	goArguments := make([]reflect.Value, 2, 2)
	goArguments[0] = reflect.ValueOf(column)
	goArguments[1] = reflect.ValueOf(mode)

	// Call the parent method.

	o.callParentMethod(o.baseClass(), "set_cell_mode", goArguments, "")

	log.Println("  Function successfully completed.")

}

/*
   If [code]true[/code] the column [code]column[/code] is checked.
*/
func (o *TreeItem) SetChecked(column int64, checked bool) {
	log.Println("Calling TreeItem.SetChecked()")

	// Build out the method's arguments
	goArguments := make([]reflect.Value, 2, 2)
	goArguments[0] = reflect.ValueOf(column)
	goArguments[1] = reflect.ValueOf(checked)

	// Call the parent method.

	o.callParentMethod(o.baseClass(), "set_checked", goArguments, "")

	log.Println("  Function successfully completed.")

}

/*
   If [code]true[/code] the TreeItem is collapsed.
*/
func (o *TreeItem) SetCollapsed(enable bool) {
	log.Println("Calling TreeItem.SetCollapsed()")

	// Build out the method's arguments
	goArguments := make([]reflect.Value, 1, 1)
	goArguments[0] = reflect.ValueOf(enable)

	// Call the parent method.

	o.callParentMethod(o.baseClass(), "set_collapsed", goArguments, "")

	log.Println("  Function successfully completed.")

}

/*

 */
func (o *TreeItem) SetCustomAsButton(column int64, enable bool) {
	log.Println("Calling TreeItem.SetCustomAsButton()")

	// Build out the method's arguments
	goArguments := make([]reflect.Value, 2, 2)
	goArguments[0] = reflect.ValueOf(column)
	goArguments[1] = reflect.ValueOf(enable)

	// Call the parent method.

	o.callParentMethod(o.baseClass(), "set_custom_as_button", goArguments, "")

	log.Println("  Function successfully completed.")

}

/*
   Sets the given column's custom background color and whether to just use it as an outline.
*/
func (o *TreeItem) SetCustomBgColor(column int64, color *Color, justOutline bool) {
	log.Println("Calling TreeItem.SetCustomBgColor()")

	// Build out the method's arguments
	goArguments := make([]reflect.Value, 3, 3)
	goArguments[0] = reflect.ValueOf(column)
	goArguments[1] = reflect.ValueOf(color)
	goArguments[2] = reflect.ValueOf(justOutline)

	// Call the parent method.

	o.callParentMethod(o.baseClass(), "set_custom_bg_color", goArguments, "")

	log.Println("  Function successfully completed.")

}

/*
   Sets the given column's custom color.
*/
func (o *TreeItem) SetCustomColor(column int64, color *Color) {
	log.Println("Calling TreeItem.SetCustomColor()")

	// Build out the method's arguments
	goArguments := make([]reflect.Value, 2, 2)
	goArguments[0] = reflect.ValueOf(column)
	goArguments[1] = reflect.ValueOf(color)

	// Call the parent method.

	o.callParentMethod(o.baseClass(), "set_custom_color", goArguments, "")

	log.Println("  Function successfully completed.")

}

/*
   Sets the given column's custom draw callback to [code]callback[/code] method on [code]object[/code].
*/
func (o *TreeItem) SetCustomDraw(column int64, object *Object, callback string) {
	log.Println("Calling TreeItem.SetCustomDraw()")

	// Build out the method's arguments
	goArguments := make([]reflect.Value, 3, 3)
	goArguments[0] = reflect.ValueOf(column)
	goArguments[1] = reflect.ValueOf(object)
	goArguments[2] = reflect.ValueOf(callback)

	// Call the parent method.

	o.callParentMethod(o.baseClass(), "set_custom_draw", goArguments, "")

	log.Println("  Function successfully completed.")

}

/*
   Sets the custom minimum height of this TreeItem.
*/
func (o *TreeItem) SetCustomMinimumHeight(height int64) {
	log.Println("Calling TreeItem.SetCustomMinimumHeight()")

	// Build out the method's arguments
	goArguments := make([]reflect.Value, 1, 1)
	goArguments[0] = reflect.ValueOf(height)

	// Call the parent method.

	o.callParentMethod(o.baseClass(), "set_custom_minimum_height", goArguments, "")

	log.Println("  Function successfully completed.")

}

/*
   If [code]true[/code] folding is disabled for this TreeItem.
*/
func (o *TreeItem) SetDisableFolding(disable bool) {
	log.Println("Calling TreeItem.SetDisableFolding()")

	// Build out the method's arguments
	goArguments := make([]reflect.Value, 1, 1)
	goArguments[0] = reflect.ValueOf(disable)

	// Call the parent method.

	o.callParentMethod(o.baseClass(), "set_disable_folding", goArguments, "")

	log.Println("  Function successfully completed.")

}

/*
   If [code]true[/code] column [code]column[/code] is editable.
*/
func (o *TreeItem) SetEditable(column int64, enabled bool) {
	log.Println("Calling TreeItem.SetEditable()")

	// Build out the method's arguments
	goArguments := make([]reflect.Value, 2, 2)
	goArguments[0] = reflect.ValueOf(column)
	goArguments[1] = reflect.ValueOf(enabled)

	// Call the parent method.

	o.callParentMethod(o.baseClass(), "set_editable", goArguments, "")

	log.Println("  Function successfully completed.")

}

/*
   If [code]true[/code] column [code]column[/code] is expanded to the right.
*/
func (o *TreeItem) SetExpandRight(column int64, enable bool) {
	log.Println("Calling TreeItem.SetExpandRight()")

	// Build out the method's arguments
	goArguments := make([]reflect.Value, 2, 2)
	goArguments[0] = reflect.ValueOf(column)
	goArguments[1] = reflect.ValueOf(enable)

	// Call the parent method.

	o.callParentMethod(o.baseClass(), "set_expand_right", goArguments, "")

	log.Println("  Function successfully completed.")

}

/*
   Sets the given column's icon [Texture].
*/
func (o *TreeItem) SetIcon(column int64, texture *Texture) {
	log.Println("Calling TreeItem.SetIcon()")

	// Build out the method's arguments
	goArguments := make([]reflect.Value, 2, 2)
	goArguments[0] = reflect.ValueOf(column)
	goArguments[1] = reflect.ValueOf(texture)

	// Call the parent method.

	o.callParentMethod(o.baseClass(), "set_icon", goArguments, "")

	log.Println("  Function successfully completed.")

}

/*
   Sets the given column's icon's maximum width.
*/
func (o *TreeItem) SetIconMaxWidth(column int64, width int64) {
	log.Println("Calling TreeItem.SetIconMaxWidth()")

	// Build out the method's arguments
	goArguments := make([]reflect.Value, 2, 2)
	goArguments[0] = reflect.ValueOf(column)
	goArguments[1] = reflect.ValueOf(width)

	// Call the parent method.

	o.callParentMethod(o.baseClass(), "set_icon_max_width", goArguments, "")

	log.Println("  Function successfully completed.")

}

/*
   Sets the given column's icon's texture region.
*/
func (o *TreeItem) SetIconRegion(column int64, region *Rect2) {
	log.Println("Calling TreeItem.SetIconRegion()")

	// Build out the method's arguments
	goArguments := make([]reflect.Value, 2, 2)
	goArguments[0] = reflect.ValueOf(column)
	goArguments[1] = reflect.ValueOf(region)

	// Call the parent method.

	o.callParentMethod(o.baseClass(), "set_icon_region", goArguments, "")

	log.Println("  Function successfully completed.")

}

/*

 */
func (o *TreeItem) SetMetadata(column int64, meta *Variant) {
	log.Println("Calling TreeItem.SetMetadata()")

	// Build out the method's arguments
	goArguments := make([]reflect.Value, 2, 2)
	goArguments[0] = reflect.ValueOf(column)
	goArguments[1] = reflect.ValueOf(meta)

	// Call the parent method.

	o.callParentMethod(o.baseClass(), "set_metadata", goArguments, "")

	log.Println("  Function successfully completed.")

}

/*

 */
func (o *TreeItem) SetRange(column int64, value float64) {
	log.Println("Calling TreeItem.SetRange()")

	// Build out the method's arguments
	goArguments := make([]reflect.Value, 2, 2)
	goArguments[0] = reflect.ValueOf(column)
	goArguments[1] = reflect.ValueOf(value)

	// Call the parent method.

	o.callParentMethod(o.baseClass(), "set_range", goArguments, "")

	log.Println("  Function successfully completed.")

}

/*

 */
func (o *TreeItem) SetRangeConfig(column int64, min float64, max float64, step float64, expr bool) {
	log.Println("Calling TreeItem.SetRangeConfig()")

	// Build out the method's arguments
	goArguments := make([]reflect.Value, 5, 5)
	goArguments[0] = reflect.ValueOf(column)
	goArguments[1] = reflect.ValueOf(min)
	goArguments[2] = reflect.ValueOf(max)
	goArguments[3] = reflect.ValueOf(step)
	goArguments[4] = reflect.ValueOf(expr)

	// Call the parent method.

	o.callParentMethod(o.baseClass(), "set_range_config", goArguments, "")

	log.Println("  Function successfully completed.")

}

/*
   If [code]true[/code] the given column is selectable.
*/
func (o *TreeItem) SetSelectable(column int64, selectable bool) {
	log.Println("Calling TreeItem.SetSelectable()")

	// Build out the method's arguments
	goArguments := make([]reflect.Value, 2, 2)
	goArguments[0] = reflect.ValueOf(column)
	goArguments[1] = reflect.ValueOf(selectable)

	// Call the parent method.

	o.callParentMethod(o.baseClass(), "set_selectable", goArguments, "")

	log.Println("  Function successfully completed.")

}

/*

 */
func (o *TreeItem) SetText(column int64, text string) {
	log.Println("Calling TreeItem.SetText()")

	// Build out the method's arguments
	goArguments := make([]reflect.Value, 2, 2)
	goArguments[0] = reflect.ValueOf(column)
	goArguments[1] = reflect.ValueOf(text)

	// Call the parent method.

	o.callParentMethod(o.baseClass(), "set_text", goArguments, "")

	log.Println("  Function successfully completed.")

}

/*
   Sets the given column's text alignment. See [code]ALIGN_*[/code] constants.
*/
func (o *TreeItem) SetTextAlign(column int64, textAlign int64) {
	log.Println("Calling TreeItem.SetTextAlign()")

	// Build out the method's arguments
	goArguments := make([]reflect.Value, 2, 2)
	goArguments[0] = reflect.ValueOf(column)
	goArguments[1] = reflect.ValueOf(textAlign)

	// Call the parent method.

	o.callParentMethod(o.baseClass(), "set_text_align", goArguments, "")

	log.Println("  Function successfully completed.")

}

/*
   Sets the given column's tooltip text.
*/
func (o *TreeItem) SetTooltip(column int64, tooltip string) {
	log.Println("Calling TreeItem.SetTooltip()")

	// Build out the method's arguments
	goArguments := make([]reflect.Value, 2, 2)
	goArguments[0] = reflect.ValueOf(column)
	goArguments[1] = reflect.ValueOf(tooltip)

	// Call the parent method.

	o.callParentMethod(o.baseClass(), "set_tooltip", goArguments, "")

	log.Println("  Function successfully completed.")

}

/*
   TreeItemImplementer is an interface for TreeItem objects.
*/
type TreeItemImplementer interface {
	class.Class
}
