//------------------------------------------------------------------------------
//   This code was generated by a tool.
//
//   Changes to this file may cause incorrect behavior and will be lost if
//   the code is regenerated. Any updates should be done in
//   "templates/*.go.template" so they can be included in the generated
//   code.
//------------------------------------------------------------------------------

package imagetexture

/*
#include <stdio.h>
#include <stdlib.h>
#include <gdnative/gdnative.h>
#include <nativescript/godot_nativescript.h>
*/
import "C"

import (
	"github.com/shadowapex/godot-go/godot/classes/class"
	"log"
	"reflect"

	"github.com/shadowapex/godot-go/godot/classes/texture"
)

/*
   A [Texture] based on an [Image]. Can be created from an [Image] with [method create_from_image].
*/
type ImageTexture struct {
	texture.Texture
}

func (o *ImageTexture) baseClass() string {
	return "ImageTexture"
}

// SetOwner will internally set the Godot object inside the struct.
// This is used to call parent methods.
func (o *ImageTexture) setOwner(object *C.godot_object) {
	o.owner = object
}

func (o *ImageTexture) getOwner() *C.godot_object {
	return o.owner
}

/*
   Undocumented
*/
func (o *ImageTexture) X_ReloadHook(rid *RID) {
	log.Println("Calling ImageTexture.X_ReloadHook()")

	// Build out the method's arguments
	goArguments := make([]reflect.Value, 1, 1)
	goArguments[0] = reflect.ValueOf(rid)

	// Call the parent method.

	o.callParentMethod(o.baseClass(), "_reload_hook", goArguments, "")

	log.Println("  Function successfully completed.")

}

/*
   Create a new [ImageTexture] with "width" and "height". "format" one of [Image].FORMAT_*. "flags" one or more of [Texture].FLAG_*.
*/
func (o *ImageTexture) Create(width int64, height int64, format int64, flags int64) {
	log.Println("Calling ImageTexture.Create()")

	// Build out the method's arguments
	goArguments := make([]reflect.Value, 4, 4)
	goArguments[0] = reflect.ValueOf(width)
	goArguments[1] = reflect.ValueOf(height)
	goArguments[2] = reflect.ValueOf(format)
	goArguments[3] = reflect.ValueOf(flags)

	// Call the parent method.

	o.callParentMethod(o.baseClass(), "create", goArguments, "")

	log.Println("  Function successfully completed.")

}

/*
   Create a new [ImageTexture] from an [Image] with "flags" from [Texture].FLAG_*.
*/
func (o *ImageTexture) CreateFromImage(image *Image, flags int64) {
	log.Println("Calling ImageTexture.CreateFromImage()")

	// Build out the method's arguments
	goArguments := make([]reflect.Value, 2, 2)
	goArguments[0] = reflect.ValueOf(image)
	goArguments[1] = reflect.ValueOf(flags)

	// Call the parent method.

	o.callParentMethod(o.baseClass(), "create_from_image", goArguments, "")

	log.Println("  Function successfully completed.")

}

/*
   Return the format of the [ImageTexture], one of [Image].FORMAT_*.
*/
func (o *ImageTexture) GetFormat() int64 {
	log.Println("Calling ImageTexture.GetFormat()")

	// Build out the method's arguments
	goArguments := make([]reflect.Value, 0, 0)

	// Call the parent method.

	goRet := class.CallParentMethod(o, o.baseClass(), "get_format", goArguments, "int64")

	returnValue := goRet.Interface().(int64)

	log.Println("  Got return value: ", returnValue)
	return returnValue

}

/*
   Return the storage quality for [ImageTexture].STORAGE_COMPRESS_LOSSY.
*/
func (o *ImageTexture) GetLossyStorageQuality() float64 {
	log.Println("Calling ImageTexture.GetLossyStorageQuality()")

	// Build out the method's arguments
	goArguments := make([]reflect.Value, 0, 0)

	// Call the parent method.

	goRet := class.CallParentMethod(o, o.baseClass(), "get_lossy_storage_quality", goArguments, "float64")

	returnValue := goRet.Interface().(float64)

	log.Println("  Got return value: ", returnValue)
	return returnValue

}

/*
   Return the storage type. One of [ImageTexture].STORAGE_*.
*/
func (o *ImageTexture) GetStorage() int64 {
	log.Println("Calling ImageTexture.GetStorage()")

	// Build out the method's arguments
	goArguments := make([]reflect.Value, 0, 0)

	// Call the parent method.

	goRet := class.CallParentMethod(o, o.baseClass(), "get_storage", goArguments, "int64")

	returnValue := goRet.Interface().(int64)

	log.Println("  Got return value: ", returnValue)
	return returnValue

}

/*
   Load an [ImageTexture].
*/
func (o *ImageTexture) Load(path string) {
	log.Println("Calling ImageTexture.Load()")

	// Build out the method's arguments
	goArguments := make([]reflect.Value, 1, 1)
	goArguments[0] = reflect.ValueOf(path)

	// Call the parent method.

	o.callParentMethod(o.baseClass(), "load", goArguments, "")

	log.Println("  Function successfully completed.")

}

/*
   Set the [Image] of this [ImageTexture].
*/
func (o *ImageTexture) SetData(image *Image) {
	log.Println("Calling ImageTexture.SetData()")

	// Build out the method's arguments
	goArguments := make([]reflect.Value, 1, 1)
	goArguments[0] = reflect.ValueOf(image)

	// Call the parent method.

	o.callParentMethod(o.baseClass(), "set_data", goArguments, "")

	log.Println("  Function successfully completed.")

}

/*
   Set the storage quality in case of [ImageTexture].STORAGE_COMPRESS_LOSSY.
*/
func (o *ImageTexture) SetLossyStorageQuality(quality float64) {
	log.Println("Calling ImageTexture.SetLossyStorageQuality()")

	// Build out the method's arguments
	goArguments := make([]reflect.Value, 1, 1)
	goArguments[0] = reflect.ValueOf(quality)

	// Call the parent method.

	o.callParentMethod(o.baseClass(), "set_lossy_storage_quality", goArguments, "")

	log.Println("  Function successfully completed.")

}

/*
   Resizes the [code]ImageTexture[/code] to the specified dimensions.
*/
func (o *ImageTexture) SetSizeOverride(size *Vector2) {
	log.Println("Calling ImageTexture.SetSizeOverride()")

	// Build out the method's arguments
	goArguments := make([]reflect.Value, 1, 1)
	goArguments[0] = reflect.ValueOf(size)

	// Call the parent method.

	o.callParentMethod(o.baseClass(), "set_size_override", goArguments, "")

	log.Println("  Function successfully completed.")

}

/*
   Set the storage type. One of [ImageTexture].STORAGE_*.
*/
func (o *ImageTexture) SetStorage(mode int64) {
	log.Println("Calling ImageTexture.SetStorage()")

	// Build out the method's arguments
	goArguments := make([]reflect.Value, 1, 1)
	goArguments[0] = reflect.ValueOf(mode)

	// Call the parent method.

	o.callParentMethod(o.baseClass(), "set_storage", goArguments, "")

	log.Println("  Function successfully completed.")

}

/*
   ImageTextureImplementer is an interface for ImageTexture objects.
*/
type ImageTextureImplementer interface {
	class.Class
}
