//------------------------------------------------------------------------------
//   This code was generated by a tool.
//
//   Changes to this file may cause incorrect behavior and will be lost if
//   the code is regenerated. Any updates should be done in
//   "templates/*.go.template" so they can be included in the generated
//   code.
//------------------------------------------------------------------------------

package streamtexture

/*
#include <stdio.h>
#include <stdlib.h>
#include <gdnative/gdnative.h>
#include <nativescript/godot_nativescript.h>
*/
import "C"

import (
	"github.com/shadowapex/godot-go/godot/classes/class"
	"log"
	"reflect"

	"github.com/shadowapex/godot-go/godot/classes/texture"
)

/*

 */
type StreamTexture struct {
	texture.Texture
}

func (o *StreamTexture) baseClass() string {
	return "StreamTexture"
}

// SetOwner will internally set the Godot object inside the struct.
// This is used to call parent methods.
func (o *StreamTexture) setOwner(object *C.godot_object) {
	o.owner = object
}

func (o *StreamTexture) getOwner() *C.godot_object {
	return o.owner
}

/*

 */
func (o *StreamTexture) GetLoadPath() string {
	log.Println("Calling StreamTexture.GetLoadPath()")

	// Build out the method's arguments
	goArguments := make([]reflect.Value, 0, 0)

	// Call the parent method.

	goRet := class.CallParentMethod(o, o.baseClass(), "get_load_path", goArguments, "string")

	returnValue := goRet.Interface().(string)

	log.Println("  Got return value: ", returnValue)
	return returnValue

}

/*

 */
func (o *StreamTexture) Load(path string) int64 {
	log.Println("Calling StreamTexture.Load()")

	// Build out the method's arguments
	goArguments := make([]reflect.Value, 1, 1)
	goArguments[0] = reflect.ValueOf(path)

	// Call the parent method.

	goRet := class.CallParentMethod(o, o.baseClass(), "load", goArguments, "int64")

	returnValue := goRet.Interface().(int64)

	log.Println("  Got return value: ", returnValue)
	return returnValue

}

/*
   StreamTextureImplementer is an interface for StreamTexture objects.
*/
type StreamTextureImplementer interface {
	class.Class
}
