//------------------------------------------------------------------------------
//   This code was generated by a tool.
//
//   Changes to this file may cause incorrect behavior and will be lost if
//   the code is regenerated. Any updates should be done in
//   "templates/*.go.template" so they can be included in the generated
//   code.
//------------------------------------------------------------------------------

package curvetexture

/*
#include <stdio.h>
#include <stdlib.h>
#include <gdnative/gdnative.h>
#include <nativescript/godot_nativescript.h>
*/
import "C"

import (
	"github.com/shadowapex/godot-go/godot/classes/class"
	"log"
	"reflect"

	"github.com/shadowapex/godot-go/godot/classes/texture"
)

/*

 */
type CurveTexture struct {
	texture.Texture
}

func (o *CurveTexture) baseClass() string {
	return "CurveTexture"
}

// SetOwner will internally set the Godot object inside the struct.
// This is used to call parent methods.
func (o *CurveTexture) setOwner(object *C.godot_object) {
	o.owner = object
}

func (o *CurveTexture) getOwner() *C.godot_object {
	return o.owner
}

/*
   Undocumented
*/
func (o *CurveTexture) X_Update() {
	log.Println("Calling CurveTexture.X_Update()")

	// Build out the method's arguments
	goArguments := make([]reflect.Value, 0, 0)

	// Call the parent method.

	o.callParentMethod(o.baseClass(), "_update", goArguments, "")

	log.Println("  Function successfully completed.")

}

/*

 */
func (o *CurveTexture) GetCurve() *Curve {
	log.Println("Calling CurveTexture.GetCurve()")

	// Build out the method's arguments
	goArguments := make([]reflect.Value, 0, 0)

	// Call the parent method.

	goRet := class.CallParentMethod(o, o.baseClass(), "get_curve", goArguments, "*Curve")

	returnValue := goRet.Interface().(*Curve)

	log.Println("  Got return value: ", returnValue)
	return returnValue

}

/*

 */
func (o *CurveTexture) SetCurve(curve *Curve) {
	log.Println("Calling CurveTexture.SetCurve()")

	// Build out the method's arguments
	goArguments := make([]reflect.Value, 1, 1)
	goArguments[0] = reflect.ValueOf(curve)

	// Call the parent method.

	o.callParentMethod(o.baseClass(), "set_curve", goArguments, "")

	log.Println("  Function successfully completed.")

}

/*

 */
func (o *CurveTexture) SetWidth(width int64) {
	log.Println("Calling CurveTexture.SetWidth()")

	// Build out the method's arguments
	goArguments := make([]reflect.Value, 1, 1)
	goArguments[0] = reflect.ValueOf(width)

	// Call the parent method.

	o.callParentMethod(o.baseClass(), "set_width", goArguments, "")

	log.Println("  Function successfully completed.")

}

/*
   CurveTextureImplementer is an interface for CurveTexture objects.
*/
type CurveTextureImplementer interface {
	class.Class
}
