//------------------------------------------------------------------------------
//   This code was generated by a tool.
//
//   Changes to this file may cause incorrect behavior and will be lost if
//   the code is regenerated. Any updates should be done in
//   "templates/*.go.template" so they can be included in the generated
//   code.
//------------------------------------------------------------------------------

package visualscriptiterator

/*
#include <stdio.h>
#include <stdlib.h>
#include <gdnative/gdnative.h>
#include <nativescript/godot_nativescript.h>
*/
import "C"

import (
	"github.com/shadowapex/godot-go/godot/classes/class"
	"log"
	"reflect"

	"github.com/shadowapex/godot-go/godot/classes/visualscriptnode"
)

/*
   This node steps through each item in a given input. Input can be any sequence data type, such as an [Array] or [String]. When each item has been processed, execution passed out the [code]exit[/code] Sequence port. [b]Input Ports:[/b] - Sequence: [code]for (elem) in (input)[/code] - Data (variant): [code]input[/code] [b]Output Ports:[/b] - Sequence: [code]each[/code] - Sequence: [code]exit[/code] - Data (variant): [code]elem[/code]
*/
type VisualScriptIterator struct {
	visualscriptnode.VisualScriptNode
}

func (o *VisualScriptIterator) baseClass() string {
	return "VisualScriptIterator"
}

// SetOwner will internally set the Godot object inside the struct.
// This is used to call parent methods.
func (o *VisualScriptIterator) setOwner(object *C.godot_object) {
	o.owner = object
}

func (o *VisualScriptIterator) getOwner() *C.godot_object {
	return o.owner
}

/*
   VisualScriptIteratorImplementer is an interface for VisualScriptIterator objects.
*/
type VisualScriptIteratorImplementer interface {
	class.Class
}
